# arguments for dataset
dataset: flare22
nclass: 14 
crop_size: [64, 128, 128]
val_patch_size: [64, 160, 160]

# arguments for training
epochs: 500
batch_size: 6   # per GPU x 2 GPUs, must be even because of the cutmix!
lr: 0.1
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95


# arguments for model
model: unet_3d
backbone: unet_3d
baseline: fixmatch
lock_backbone: False